### ISSUE TITLE
Backlight level cannot be changed in LiveCD

### ISSUE THREAD

**Issue by jekhor** [jekhor/yogabook-linux#12]
Seems that lpss PWM driver is loaded after i915 and last one cannot find 'pwm_backlight' PWM chip.

**Comment by TiNredmc** [comment]
Hi. Can you try this ? https://techtablets.com/forum/reply/69539/

**Comment by TiNredmc** [comment]
I tried. It works. Add pwm_lpss and pwm_lpss_platform to /etc/initramfs-tools/modules rhen update-initramfs -u

**Comment by TiNredmc** [comment]
Auto brightness also working.

**Comment by ThongSong7** [comment]
@TiNredmc : It works well!
