### ISSUE TITLE
The button for switching keyboard<->wacom not working

### ISSUE THREAD

**Issue by BigET** [jekhor/yogabook-linux#14]
The button that is in the same place with the "pen" led.
In windows is used to switch between "halo keyboard" mode and wacom digitizer.
I cannot find any input that will trigger some event.
like volume keys and power key that are available through the input interface even if they are gpio.
I have a YB1-X91L

**Comment by jekhor** [comment]
Now it is fixed in LiveCD 5.10.2 release
