### ISSUE TITLE
Live-CD not booting

### ISSUE THREAD

**Issue by Piggeldi2013** [jekhor/yogabook-linux#17]
Hi there!

I downloaded the latest version of the Live-CD and used Etcher to bring it to an USB-Stick.

On trying to boot, I get the following messages at the GRUB boot screen:
```
`Booting 'Live System'

error: /live/vmlinuz-5.10.0-rc3-amd64 has invalid signature.
error: you need to load the kernel first.

Press any key to continue...

Failed to boot both default and fallback entries.`
```

So, tried to install to a MicroSD card and boot from that - having the same issue.

Any help much appreciated!

Thnaks,
Carsten

**Comment by TiNredmc** [comment]
You need to disable secure boot in bios.

**Comment by TiNredmc** [comment]
I had done the guide signing the vmzlinuz to boot with secure boot, https://1drv.ms/t/s!AsNsKN33FBTv3XdlvLWCyrFAlcJD I might consider create gist for this one soon.

**Comment by Piggeldi2013** [comment]
Hi @TiNredmc ,
sorry, I missed that - Live CD is booting with secure boot disabled.
Thanks for your help!

Best,
Carsten
