### ISSUE TITLE
Persistent Live

### ISSUE THREAD

**Issue by VaeD78** [jekhor/yogabook-linux#21]
Hello,

Thanks for your work ! i'm very happy to run Debian on my Yogabook !!

I has installed the iso on sd card to boot on. Is it possible to have persistent mode on the live iso ? i would like to use standard partition to mount /home.

**Comment by TiNredmc** [comment]
You need to boot the installer iso from external usb disk, and install onto your Micro SD card to get the proper installation not the CD persistence image

**Comment by VaeD78** [comment]
Thanks for the reply but there is no installer with this image ?
Do you know how to install ?

**Comment by TiNredmc** [comment]
I'm not sure about the latest image. But as far as I know, he (maintainer) compiled the setup iso image, but it will boot automatically into the first boot option (which is live cd) infact you can install the debian from live system. There's the executable shortcut in GNOME applications launcher.

**Comment by VaeD78** [comment]
Ok, i found it in app launcher... but it crash

And no entry for installation in boot menu... i will waiting for next iso

**Comment by TiNredmc** [comment]
Did you have any flash drive ? It's better to boot of external usb storage. If the installer crashed again, Try to re-download the image and re-burn the image then boot of it.

**Comment by VaeD78** [comment]
I'll try.

I took the iso livecd-5.10.2, I didn't see but jekhor wrote :

> Known Issues:  There is no debian installer included into the image.

 https://github.com/jekhor/yogabook-linux/releases/tag/livecd-5.10.2
