### ISSUE TITLE
Clean Debian stable installation: audio doesn't work

### ISSUE THREAD

**Issue by marco-04** [jekhor/yogabook-linux#33]
Hello! I installed the latest debian stable version available 11.5.0 with non-free firmware included, and I was able to get both the keyboard and the pen button to work, by installing the packages and then switching the main boot option in grub with the custom kernel, but I really don't know how to make sound work (even with the packages installed), as on the live cd it works as expected.
On alsamixer I found that there is an Intel audio card which is not controllable from alsa, and then the yogabook one from the alsa-ucm package which has both headphones and speakers set to off.
Does anyone have any clue of what may be the problem? Thanks in advance, and thanks jekhor for the wonderful work with the drivers!

**Comment by marco-04** [comment]
I just noticed that every time I get into a tty, I get a bunch of errors, and the last one seems related to audio

![20221029_203040.jpg](https://user-images.githubusercontent.com/61947904/198847446-ae827f9f-5fb1-4f6e-8613-0da42c031e45.jpg)

I don't know if that may help tho

**Comment by jekhor** [comment]
Which kernel version is used?

Try this .debs: https://github.com/jekhor/yogabook-linux-kernel/releases/tag/v6.0.5-yogabook1

**Comment by marco-04** [comment]
Unfortunately not. It fixed the wrong orientation at startup, but it also made the keyboard/pen mode switching a bit slower.
Regarding audio I only see as output a "Dummy output" and I still get some error messages on every tty. Still the same on alsamixer. I tried a dpkg-reconfigure on the package and uninstalling and reinstalling

![20221102_205447.jpg](https://user-images.githubusercontent.com/61947904/199591340-b0dfb6f4-8155-4b85-b5d8-f0fd305336c3.jpg)
![20221102_205654.jpg](https://user-images.githubusercontent.com/61947904/199591367-48054f69-9931-4953-9e02-a7d9c0cf668f.jpg)

**Comment by marco-04** [comment]
Forgot to mention, before I was using the 5.10.0-19 kernel on the latest release on this repo

**Comment by jekhor** [comment]
It seems that you don't have firmware package, I will  check exactly name
later.

ср, 2 ліс 2022, 22:09 карыстальнік marco-04 ***@***.***>
напісаў:

**Comment by marco-04** [comment]
I'm so dumb. I found it, it was firmware-intel-sound, rebooted and now it works. Thanks for helping me!
