### ISSUE TITLE
[SOLVED] Debian 13 (trixie) and Yogabook YB1-X91F

### ISSUE THREAD

**Issue by MonsieurZorglub** [jekhor/yogabook-linux#42]
First of all: amazing work. It gives me the opportunity to revive my YogaBook from hibernation and use it as GPS plotter with OpenCPN and NMEA. Great. 

After some tries with different distributions I finally came up with giving Debian 13 (trixie) a try. My path of success was the following:

- Debian 12 (bookworm) Live ISO (Gnome) on USB boot stick
- Install Debian from within the Live system - any direct installation of either Ubuntu, Debian and also the ISO here failed for whatever reason (scrambled screen, problems with squasfs etc.)
- Once installed the natural `sudo apt clean && sudo apt update && sudo apt dist-upgrade -y && sudo apt autoremove -y && sudo reboot`
- This will take some time, so make sure to disable any energy saving setting so that the screen wont go out or whatever; if not I wasnt able to revive the Yogabook - and had to restart allover :-(
- After the reboot DO NOT apply the Yogabook kernel yet. First, upgrade to Debian 13 as described here: https://gist.github.com/yorickdowne/3cecc7b424ce241b173510e36754af47
- Which was nothing more than changing the repository to trixie: `sudo sed -i 's/bookworm/trixie/g' /etc/apt/sources.list`
- Apply it to all 3rd-parties: `sudo find /etc/apt/sources.list.d -type f -exec sed -i 's/bookworm/trixie/g' {} \;`
- And eventually update to trixie: `sudo apt update && sudo apt dist-upgrade && sudo apt autoremove -y && sudo apt reboot`
- Now I applied Steps 7 to 11 from the OS-Installation part (https://github.com/jekhor/yogabook-linux?tab=readme-ov-file#os-installation)
- Also https://github.com/jekhor/yogabook-linux/issues/41#issuecomment-2323297989
- Also https://github.com/jekhor/yogabook-linux/issues/40#issue-2483059338

Almost everything is working:

- the newest Wifi firmware is already in Debian 13 (https://wiki.debian.org/brcmfmac), so no need to apply any `sudo apt install firmware-brcm<whatever>`
- after https://github.com/jekhor/yogabook-linux/issues/34#issuecomment-2282896483 the keyboard brightness can be controlled
- sound is there etc

What is not working:
- Camera (I dont care, as I dont need it)
- Screen Brightness - although applied the latest firmware files as described earlier (are there any newer probably for trixie?) and updated grub it wont work. I wont give up and will report later, but nevertheless I'm very happy with the Yogabook now running flawlessly with Debian 13.

**Comment by MonsieurZorglub** [comment]
**Finally I got the screen brightness working** - but not with all the grub kernel params floating around like acpi_backlight_something etc. None of them did work at all.

However this is working for me: https://github.com/udifuchs/icc-brightness

With one major change: after `sudo make install` you need to alter `/usr/local/bin/icc-brightness`

`BACKLIGHT_PATH = '/sys/class/backlight/intel_backlight'`

to in my case

`BACKLIGHT_PATH = '/sys/class/backlight/acpi_video0`

I have to say, I kept all the grub params, just in case they alter anything and I'm too lazy.

Now, both the Fn+F5/ Fn+F6 are working, as well as the brightness control slider in the quick settings.

**Comment by m-l-s0** [comment]
Any Idea how to get the brightness control working on Kde/plasma?
I applied the solution and thought it just did not work, but it does work on gnome, just not on plasma (both using wayland).

**Comment by MonsieurZorglub** [comment]
No idea. Also, finally I decided to sell my Yogabook. So, I cannot contribute to it anymore. Srry.

**Comment by RiccardoPP** [comment]
> Any Idea how to get the brightness control working on Kde/plasma? I applied the solution and thought it just did not work, but it does work on gnome, just not on plasma (both using wayland).

@m-l-s0 Same issue here. Have you solved?

**Comment by urufu765** [comment]
@m-l-s0 @RiccardoPP If y'all haven't yet fixed this issue, I believe I found the solution.
Though if someone could double check my solution, that'd be grand.

1. First, do step 1 from #40 (if you already modified the boot config from step 2 onwards, undo that by uncommenting `GRUB_CMDLINE_LINUX_DEFAULT="quiet"` or whatever your default was and commenting your modification)
3. Edit initramfs preloader
```bash
sudo nano /etc/initramfs-tools/modules
```
3. Append these two lines at the end of the file
```conf
pwm-lpss
pwm-lpss-platform
```
4. Save with `Ctrl`+`X`, then `Y`, then `Enter`
5. Update initramfs
```bash
sudo update-initramfs -u
```
6. Reboot
```bash
sudo reboot
```
