### ISSUE TITLE
Implement sound support

### ISSUE THREAD

**Issue by jekhor** [jekhor/yogabook-linux#6]
- [x] Found how to power up RT5677 codec (now it doesn't available via I2C but should be at I2C1, 0x2c).
- [x] Write ACPI match and board support code for Intel Cherry Trail and RT5677 combination (there is first version exist)
- [x] Add support for TS3A227E accessory detector and configuration switch (there is a driver in mainline kernel but Yoga Book doesn't have separated ACPI entry for this chip). I2C1, 0x3b.

**Comment by TiNredmc** [comment]
Hi. I almost get the audio works (I believe). Only thing that I need is the alsa ucm config. can be found on internet but all of them won't work. always stuck at this error 

`ALSA lib main.c:438:(execute_sequence) unable to execute cset 'name='Speaker Switch' on'`

`ALSA lib main.c:1712:(set_verb_user) error: failed to initialize new use case: HiFi`

`alsaucm: error failed to set _verb=HiFi: No such file or directory`

**Comment by sasha2484** [comment]
Hi. Someone was able to turn on the sound? I am following the project

**Comment by TiNredmc** [comment]
> Hi. Someone was able to turn on the sound? I am following the project

Not yet but almost, I planned to port the driver from android kernel and make the loadable module, but RN I'm using kernel 5.1, soon will move to 5.1.16 (under the 5.1.16)

**Comment by sasha2484** [comment]
Thank. Are looking forward to.

**Comment by TiNredmc** [comment]
FYI a little bit off topic, recently the Front facing camera (ov2740) just has the driver in latest kernel source.

**Comment by jekhor** [comment]
Sound playback working, microphones still not tested (please create separated issue if recording doesn't work).
